version: '3.8'

services:
  app:
    build:
      context: .   # 현재 디렉토리의 Dockerfile로 빌드
    container_name: spring_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gaehwa
      SPRING_DATASOURCE_USERNAME: gaehwa
      SPRING_DATASOURCE_PASSWORD: 980301
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    restart: always

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: gaehwa
      POSTGRES_PASSWORD: 980301
      POSTGRES_DB: gaehwa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
